// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ApiData.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace AnyeSoft.Common.Service {

  /// <summary>Holder for reflection information generated from ApiData.proto</summary>
  public static partial class ApiDataReflection {

    #region Descriptor
    /// <summary>File descriptor for ApiData.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ApiDataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1BcGlEYXRhLnByb3RvEhdBbnllU29mdC5Db21tb24uU2VydmljZSKqAQoK",
            "QVBJUmVxdWVzdBIPCgdBcGlQYXRoGAEgASgJEgwKBERhdGEYAiABKAkSDQoF",
            "QXBwSUQYAyABKAkSDAoEU2lnbhgEIAEoCRIMCgRUaW1lGAUgASgDEg0KBVRv",
            "a2VuGAYgASgJEhEKCUZpbGVCbG9jaxgHIAEoBRIaChJGaWxlQmxvY2tMYXN0",
            "SW5kZXgYCCABKAUSFAoMRmlsZUNvbnRlbnRzGAkgASgMIogBCghBUElSZXBs",
            "eRIMCgRDb2RlGAEgASgFEgwKBERhdGEYAiABKAkSCwoDTXNnGAMgASgJEg4K",
            "BkFjdGlvbhgEIAEoCRIRCglGaWxlQmxvY2sYBSABKAUSGgoSRmlsZUJsb2Nr",
            "TGFzdEluZGV4GAYgASgFEhQKDEZpbGVDb250ZW50cxgHIAEoDDKuAQoEZ1JQ",
            "QxJQCgRFeGVjEiMuQW55ZVNvZnQuQ29tbW9uLlNlcnZpY2UuQVBJUmVxdWVz",
            "dBohLkFueWVTb2Z0LkNvbW1vbi5TZXJ2aWNlLkFQSVJlcGx5IgASVAoEQ2hh",
            "dBIjLkFueWVTb2Z0LkNvbW1vbi5TZXJ2aWNlLkFQSVJlcXVlc3QaIS5Bbnll",
            "U29mdC5Db21tb24uU2VydmljZS5BUElSZXBseSIAKAEwAWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::AnyeSoft.Common.Service.APIRequest), global::AnyeSoft.Common.Service.APIRequest.Parser, new[]{ "ApiPath", "Data", "AppID", "Sign", "Time", "Token", "FileBlock", "FileBlockLastIndex", "FileContents" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::AnyeSoft.Common.Service.APIReply), global::AnyeSoft.Common.Service.APIReply.Parser, new[]{ "Code", "Data", "Msg", "Action", "FileBlock", "FileBlockLastIndex", "FileContents" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class APIRequest : pb::IMessage<APIRequest> {
    private static readonly pb::MessageParser<APIRequest> _parser = new pb::MessageParser<APIRequest>(() => new APIRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<APIRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AnyeSoft.Common.Service.ApiDataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public APIRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public APIRequest(APIRequest other) : this() {
      apiPath_ = other.apiPath_;
      data_ = other.data_;
      appID_ = other.appID_;
      sign_ = other.sign_;
      time_ = other.time_;
      token_ = other.token_;
      fileBlock_ = other.fileBlock_;
      fileBlockLastIndex_ = other.fileBlockLastIndex_;
      fileContents_ = other.fileContents_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public APIRequest Clone() {
      return new APIRequest(this);
    }

    /// <summary>Field number for the "ApiPath" field.</summary>
    public const int ApiPathFieldNumber = 1;
    private string apiPath_ = "";
    /// <summary>
    ///操作地址(类似于web地址方式,如:/api/login)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ApiPath {
      get { return apiPath_; }
      set {
        apiPath_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Data" field.</summary>
    public const int DataFieldNumber = 2;
    private string data_ = "";
    /// <summary>
    ///数据(一般是json数据)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Data {
      get { return data_; }
      set {
        data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "AppID" field.</summary>
    public const int AppIDFieldNumber = 3;
    private string appID_ = "";
    /// <summary>
    ///商户ID(用于请求接口,配合SecretKey使用)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string AppID {
      get { return appID_; }
      set {
        appID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Sign" field.</summary>
    public const int SignFieldNumber = 4;
    private string sign_ = "";
    /// <summary>
    ///电子签名
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Sign {
      get { return sign_; }
      set {
        sign_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Time" field.</summary>
    public const int TimeFieldNumber = 5;
    private long time_;
    /// <summary>
    ///时间戳
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Time {
      get { return time_; }
      set {
        time_ = value;
      }
    }

    /// <summary>Field number for the "Token" field.</summary>
    public const int TokenFieldNumber = 6;
    private string token_ = "";
    /// <summary>
    ///用户Token
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Token {
      get { return token_; }
      set {
        token_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "FileBlock" field.</summary>
    public const int FileBlockFieldNumber = 7;
    private int fileBlock_;
    /// <summary>
    ///文件块(用于文件上传等)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int FileBlock {
      get { return fileBlock_; }
      set {
        fileBlock_ = value;
      }
    }

    /// <summary>Field number for the "FileBlockLastIndex" field.</summary>
    public const int FileBlockLastIndexFieldNumber = 8;
    private int fileBlockLastIndex_;
    /// <summary>
    ///文件块最后索引(用于文件上传等)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int FileBlockLastIndex {
      get { return fileBlockLastIndex_; }
      set {
        fileBlockLastIndex_ = value;
      }
    }

    /// <summary>Field number for the "FileContents" field.</summary>
    public const int FileContentsFieldNumber = 9;
    private pb::ByteString fileContents_ = pb::ByteString.Empty;
    /// <summary>
    ///文件内容字节(用于文件上传等)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString FileContents {
      get { return fileContents_; }
      set {
        fileContents_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as APIRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(APIRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ApiPath != other.ApiPath) return false;
      if (Data != other.Data) return false;
      if (AppID != other.AppID) return false;
      if (Sign != other.Sign) return false;
      if (Time != other.Time) return false;
      if (Token != other.Token) return false;
      if (FileBlock != other.FileBlock) return false;
      if (FileBlockLastIndex != other.FileBlockLastIndex) return false;
      if (FileContents != other.FileContents) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ApiPath.Length != 0) hash ^= ApiPath.GetHashCode();
      if (Data.Length != 0) hash ^= Data.GetHashCode();
      if (AppID.Length != 0) hash ^= AppID.GetHashCode();
      if (Sign.Length != 0) hash ^= Sign.GetHashCode();
      if (Time != 0L) hash ^= Time.GetHashCode();
      if (Token.Length != 0) hash ^= Token.GetHashCode();
      if (FileBlock != 0) hash ^= FileBlock.GetHashCode();
      if (FileBlockLastIndex != 0) hash ^= FileBlockLastIndex.GetHashCode();
      if (FileContents.Length != 0) hash ^= FileContents.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ApiPath.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ApiPath);
      }
      if (Data.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Data);
      }
      if (AppID.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(AppID);
      }
      if (Sign.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Sign);
      }
      if (Time != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(Time);
      }
      if (Token.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Token);
      }
      if (FileBlock != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(FileBlock);
      }
      if (FileBlockLastIndex != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(FileBlockLastIndex);
      }
      if (FileContents.Length != 0) {
        output.WriteRawTag(74);
        output.WriteBytes(FileContents);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ApiPath.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ApiPath);
      }
      if (Data.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Data);
      }
      if (AppID.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AppID);
      }
      if (Sign.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Sign);
      }
      if (Time != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Time);
      }
      if (Token.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Token);
      }
      if (FileBlock != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(FileBlock);
      }
      if (FileBlockLastIndex != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(FileBlockLastIndex);
      }
      if (FileContents.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(FileContents);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(APIRequest other) {
      if (other == null) {
        return;
      }
      if (other.ApiPath.Length != 0) {
        ApiPath = other.ApiPath;
      }
      if (other.Data.Length != 0) {
        Data = other.Data;
      }
      if (other.AppID.Length != 0) {
        AppID = other.AppID;
      }
      if (other.Sign.Length != 0) {
        Sign = other.Sign;
      }
      if (other.Time != 0L) {
        Time = other.Time;
      }
      if (other.Token.Length != 0) {
        Token = other.Token;
      }
      if (other.FileBlock != 0) {
        FileBlock = other.FileBlock;
      }
      if (other.FileBlockLastIndex != 0) {
        FileBlockLastIndex = other.FileBlockLastIndex;
      }
      if (other.FileContents.Length != 0) {
        FileContents = other.FileContents;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ApiPath = input.ReadString();
            break;
          }
          case 18: {
            Data = input.ReadString();
            break;
          }
          case 26: {
            AppID = input.ReadString();
            break;
          }
          case 34: {
            Sign = input.ReadString();
            break;
          }
          case 40: {
            Time = input.ReadInt64();
            break;
          }
          case 50: {
            Token = input.ReadString();
            break;
          }
          case 56: {
            FileBlock = input.ReadInt32();
            break;
          }
          case 64: {
            FileBlockLastIndex = input.ReadInt32();
            break;
          }
          case 74: {
            FileContents = input.ReadBytes();
            break;
          }
        }
      }
    }

  }

  public sealed partial class APIReply : pb::IMessage<APIReply> {
    private static readonly pb::MessageParser<APIReply> _parser = new pb::MessageParser<APIReply>(() => new APIReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<APIReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AnyeSoft.Common.Service.ApiDataReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public APIReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public APIReply(APIReply other) : this() {
      code_ = other.code_;
      data_ = other.data_;
      msg_ = other.msg_;
      action_ = other.action_;
      fileBlock_ = other.fileBlock_;
      fileBlockLastIndex_ = other.fileBlockLastIndex_;
      fileContents_ = other.fileContents_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public APIReply Clone() {
      return new APIReply(this);
    }

    /// <summary>Field number for the "Code" field.</summary>
    public const int CodeFieldNumber = 1;
    private int code_;
    /// <summary>
    ///返回结果(0:成功,其他值:错误)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Code {
      get { return code_; }
      set {
        code_ = value;
      }
    }

    /// <summary>Field number for the "Data" field.</summary>
    public const int DataFieldNumber = 2;
    private string data_ = "";
    /// <summary>
    ///返回数据(一般是json数据)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Data {
      get { return data_; }
      set {
        data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Msg" field.</summary>
    public const int MsgFieldNumber = 3;
    private string msg_ = "";
    /// <summary>
    ///提示信息
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Msg {
      get { return msg_; }
      set {
        msg_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Action" field.</summary>
    public const int ActionFieldNumber = 4;
    private string action_ = "";
    /// <summary>
    ///操作类型(用于客户端执行某些操作)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Action {
      get { return action_; }
      set {
        action_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "FileBlock" field.</summary>
    public const int FileBlockFieldNumber = 5;
    private int fileBlock_;
    /// <summary>
    ///文件块(用于文件下载等)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int FileBlock {
      get { return fileBlock_; }
      set {
        fileBlock_ = value;
      }
    }

    /// <summary>Field number for the "FileBlockLastIndex" field.</summary>
    public const int FileBlockLastIndexFieldNumber = 6;
    private int fileBlockLastIndex_;
    /// <summary>
    ///文件块最后索引(用于文件上传等)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int FileBlockLastIndex {
      get { return fileBlockLastIndex_; }
      set {
        fileBlockLastIndex_ = value;
      }
    }

    /// <summary>Field number for the "FileContents" field.</summary>
    public const int FileContentsFieldNumber = 7;
    private pb::ByteString fileContents_ = pb::ByteString.Empty;
    /// <summary>
    ///文件内容字节(用于文件下载等)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString FileContents {
      get { return fileContents_; }
      set {
        fileContents_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as APIReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(APIReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Code != other.Code) return false;
      if (Data != other.Data) return false;
      if (Msg != other.Msg) return false;
      if (Action != other.Action) return false;
      if (FileBlock != other.FileBlock) return false;
      if (FileBlockLastIndex != other.FileBlockLastIndex) return false;
      if (FileContents != other.FileContents) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Code != 0) hash ^= Code.GetHashCode();
      if (Data.Length != 0) hash ^= Data.GetHashCode();
      if (Msg.Length != 0) hash ^= Msg.GetHashCode();
      if (Action.Length != 0) hash ^= Action.GetHashCode();
      if (FileBlock != 0) hash ^= FileBlock.GetHashCode();
      if (FileBlockLastIndex != 0) hash ^= FileBlockLastIndex.GetHashCode();
      if (FileContents.Length != 0) hash ^= FileContents.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Code != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Code);
      }
      if (Data.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Data);
      }
      if (Msg.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Msg);
      }
      if (Action.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Action);
      }
      if (FileBlock != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(FileBlock);
      }
      if (FileBlockLastIndex != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(FileBlockLastIndex);
      }
      if (FileContents.Length != 0) {
        output.WriteRawTag(58);
        output.WriteBytes(FileContents);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Code != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Code);
      }
      if (Data.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Data);
      }
      if (Msg.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Msg);
      }
      if (Action.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Action);
      }
      if (FileBlock != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(FileBlock);
      }
      if (FileBlockLastIndex != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(FileBlockLastIndex);
      }
      if (FileContents.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(FileContents);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(APIReply other) {
      if (other == null) {
        return;
      }
      if (other.Code != 0) {
        Code = other.Code;
      }
      if (other.Data.Length != 0) {
        Data = other.Data;
      }
      if (other.Msg.Length != 0) {
        Msg = other.Msg;
      }
      if (other.Action.Length != 0) {
        Action = other.Action;
      }
      if (other.FileBlock != 0) {
        FileBlock = other.FileBlock;
      }
      if (other.FileBlockLastIndex != 0) {
        FileBlockLastIndex = other.FileBlockLastIndex;
      }
      if (other.FileContents.Length != 0) {
        FileContents = other.FileContents;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Code = input.ReadInt32();
            break;
          }
          case 18: {
            Data = input.ReadString();
            break;
          }
          case 26: {
            Msg = input.ReadString();
            break;
          }
          case 34: {
            Action = input.ReadString();
            break;
          }
          case 40: {
            FileBlock = input.ReadInt32();
            break;
          }
          case 48: {
            FileBlockLastIndex = input.ReadInt32();
            break;
          }
          case 58: {
            FileContents = input.ReadBytes();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
